// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA37XMTgCK6jC58nguWMrGXY_tQYsKNPY8',
    appId: '1:538973598077:web:05e1db60782e93fa7fdc14',
    messagingSenderId: '538973598077',
    projectId: 'gestor-365push2',
    authDomain: 'gestor-365push2.firebaseapp.com',
    storageBucket: 'gestor-365push2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dQ-1wmZYYoW8Nv1zLbqz-i31mbU238U',
    appId: '1:538973598077:android:12c13bd937f706d87fdc14',
    messagingSenderId: '538973598077',
    projectId: 'gestor-365push2',
    storageBucket: 'gestor-365push2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqXk7b-Fv6gpjXyJ1g50vsjxqMWqRGJwc',
    appId: '1:538973598077:ios:12d32cec09de00be7fdc14',
    messagingSenderId: '538973598077',
    projectId: 'gestor-365push2',
    storageBucket: 'gestor-365push2.firebasestorage.app',
    iosBundleId: 'com.example.gestaoBarPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqXk7b-Fv6gpjXyJ1g50vsjxqMWqRGJwc',
    appId: '1:538973598077:ios:12d32cec09de00be7fdc14',
    messagingSenderId: '538973598077',
    projectId: 'gestor-365push2',
    storageBucket: 'gestor-365push2.firebasestorage.app',
    iosBundleId: 'com.example.gestaoBarPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA37XMTgCK6jC58nguWMrGXY_tQYsKNPY8',
    appId: '1:538973598077:web:a50f7694bca537717fdc14',
    messagingSenderId: '538973598077',
    projectId: 'gestor-365push2',
    authDomain: 'gestor-365push2.firebaseapp.com',
    storageBucket: 'gestor-365push2.firebasestorage.app',
  );
}
